### ISSUE TITLE
Grid visualization code

### ISSUE THREAD

**Issue by xuyaojian123** [daniel03c1/BNeRF#12]
I see that your project home page provides a Grid visualization demo? Is the Grid visualization code open source? 
In addition, what do Top, Lateral and Front mean?
![image](https://github.com/daniel03c1/masked_wavelet_nerf/assets/51220835/84798073-c9b8-4df7-90ad-03d939680a5e)

**Comment by daniel03c1** [comment]
We utilized matplotlib to display grids. Given that each grid contains more than three channels (except for non-masked grids), we applied principal component analysis (PCA) to distill three crucial components. Subsequently, we employed these three extracted channels for visualization.

Regarding the terms "top," "lateral," and "front," they simply serve as notations for representing each perpendicular planes.

**Comment by xuyaojian123** [comment]
> I see that your project home page provides a Grid visualization demo? Is the Grid visualization code open source?
> In addition, what do Top, Lateral and Front mean?

Thanks for your answer, I was wondering if you would like to share this part of the code, I really appreciate it. my email 2100271041@email.szu.edu.cn

**Comment by daniel03c1** [comment]
Unfortunately, we do not have the visualization code at the moment. But it will not be difficult to implement. Sorry for that.

**Comment by xuyaojian123** [comment]
> Unfortunately, we do not have the visualization code at the moment. But it will not be difficult to implement. Sorry for that.

ok,thank you!
