### ISSUE TITLE
Why shrink function need to init mask？

### ISSUE THREAD

**Issue by xuyaojian123** [daniel03c1/BNeRF#15]
Why does `mask` not get a new mask also through `F.grid_sample`, but chooses to initialize mask to 1. I found that mask quickly becomes 0 during the training process. If my bbox remains unchanged, how can I train `mask` effectively? Thank you.

![image](https://github.com/daniel03c1/masked_wavelet_nerf/assets/51220835/f362290a-df73-47f2-b444-d5187187ca4f)

**Comment by daniel03c1** [comment]
Thank you for your interest. We just choose to reinitialize the mask after the shrinking process. However, I would encourage you to explore various settings, as different configurations might yield interesting results. Thank you.

**Comment by xuyaojian123** [comment]
Thank you!
