### ISSUE TITLE
About the reasons for discrete wavelet transform planes compression?

### ISSUE THREAD

**Issue by xuyaojian123** [daniel03c1/BNeRF#17]
I want to ask how you discovered that using the discrete wavelet transform on planes is good for compression without experimental verification. How should I analyze the real reasons why applying DWT to the original parameters of planes can compress, rather than directly looking at experimental results for verification?

**Comment by daniel03c1** [comment]
If I understood your question correctly, the work was inspired by various compression algorithms, as described in the paper.
