### ISSUE TITLE
TriPlane model

### ISSUE THREAD

**Issue by xuyaojian123** [daniel03c1/BNeRF#9]
Thank you great job!
parser.add_argument('--model_name', type=str, default='TensorVMSplit',
                        choices=['TensorVMSplit', 'TensorCP', 'TriPlane'])
i can unsterstand ’TensorVMSplit’，‘TensorCP’ model. What's the difference between the 'TriPlane' model with them?

**Comment by daniel03c1** [comment]
The main difference comes from the use of lines. TensoRF couples planes and vectors, while TriPlane only uses planes.

**Comment by xuyaojian123** [comment]
> The main difference comes from the use of lines. TensoRF couples planes and vectors, while TriPlane only uses planes.

ok,thank you!
